lab_6/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index , name ='index'),
    path('tambahStatus/', views.tambahStatus, name='tambahStatus')
]

lab_7/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('lab7/', views.index , name ='index'),
]

lab_8/urls.py
from django.urls import path
from . import views

app_name = 'homeBook'

urlpatterns = [
    path('book/', views.index , name ='index'),
    path('dataBuku', views.dataBuku),
]

lab_9/urls.py
from django.urls import path
from . import views

app_name = 'homeLogin'

urlpatterns = [
    path('login/', views.login_user , name ='login'),
    # path('hello/', views.hello , name ='hello'),
    # path('regist/', views.regist_user , name ='regist'),
    path('loginFinish/', views.loginFinish , name ='loginFinish'),
    path('logout/', views.logout_user, name='logout'),
]

ppw6/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('lab_6.urls')),
    path('',include('lab_7.urls')),
    path('',include('lab_8.urls')),
    path('',include('lab_9.urls')),
]

lab_6/models.py
from django.db import models

# Create your models here.
class Kabar(models.Model):
    status = models.CharField(max_length = 300)
    waktu = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.status

lab_7/models.py
from django.db import models

# Create your models here.

lab_8/models.py
from django.db import models

# Create your models here.

lab_9/models.py
from django.db import models

# Create your models here.

lab_6/forms.py
from django import forms

class Status(forms.Form):
    status = forms.CharField(label='Status',required= True, max_length=300,widget=forms.TextInput(attrs={'class':'form-control', 'placeholder': 'Enter your Status'}))

lab_6/views.py
from django.shortcuts import render, redirect
from .forms import Status
from .models import Kabar
from django.views.decorators.http import require_POST

# Create your views here
def index(request):
    list_status = Kabar.objects.order_by('-waktu')
    form = Status()
    context = {'list_status': list_status, 'form': form}
    return render(request, 'landing.html', context)

@require_POST
def tambahStatus(request):
    form = Status(request.POST)

    if form.is_valid():
        new_status = Kabar(status = request.POST['status'])
        new_status.save()
    
    return redirect ('homepage:index')

lab_7/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

lab_8/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.http import HttpResponse
import requests

# Create your views here.
def index(request):
    return render(request,'book.html')

def dataBuku(request):
    key = request.GET['key']
    url = 'https://www.googleapis.com/books/v1/volumes?q=' + key
    response = requests.get(url)
    response_json = response.json()

    return JsonResponse(response_json)

lab_9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User

from django.urls import reverse


# Create your views here.
def login_user(request):
    response = {}
    if request.method == "POST":
        user_id = request.POST['user_id']
        password = request.POST['password']
        user = authenticate(request, username=user_id, password=password)
        if user:
            login(request, user)
            return HttpResponseRedirect(reverse('homeLogin:loginFinish'))
        else:
            response["user_not_found"]= "User is doesn't exist"
            return render(request, 'login.html', response) 
            # HttpResponse("Username and Password is not created")
    else:         
        return render(request,'login.html',response)

def loginFinish(request):
    response = {}
    response['user'] = request.user
    return render(request, 'logout.html', response)

def logout_user(request):
    if request.method == "POST":
        logout(request)
    return HttpResponseRedirect(reverse('homeLogin:login'))

lab_6/templates/landing.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/style.css'%}">
    <link href="https://fonts.googleapis.com/css?family=Oswald|Quicksand&display=swap" rel="stylesheet">
    <title>TDD</title>
</head>
<body>
    <div class="status">
        <h1 style="text-align: center; margin-top: 100px; font-family: 'Oswald', sans-serif;">Hello, Apa Kabar?</h1>
        <form action="{% url 'homepage:tambahStatus'%}" method="POST" role="form" style="text-align: center; margin-top: 20px;">
            {% csrf_token %}
            <label for="status" id ="status">
                {{form.status}}
            </label>
            <button type="submit" style="font-family: 'Quicksand', sans-serif;" class="ml-2" id="submit">Submit</button>
        </form>
    </div>

    <div class="bungkus-status">
        <div class="statusOut mt-3">
            <div>
                {%for i in list_status%}
                <hr>{{i.status}}
                {%endfor%}
            </div>
        </div>
        <div class="statusOut mt-3 ml-5">
            <div>
                {%for i in list_status%}
                <hr>{{i.waktu}}
                {%endfor%}
            </div>
        </div>
    </div>
</body>
</html>

lab_7/templates/index.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static '/css/style2.css'%}">
    <link rel="stylesheet" href="{% static '/css/style.css'%}">
    <link href="https://fonts.googleapis.com/css?family=Oswald|Quicksand&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
    <link id="css1" rel="stylesheet" href="{% static '/css/style3.css'%}">
    <link id="css2" rel="stylesheet" href="{% static '/css/hhh.css'%}">
    <script src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static '/js/action.js'%}"></script>
    <title>Story7</title>
</head>
<style>
</style>
<body id="body">
    <div>
        <h1 class="mt-5 head" style="text-align: center; font-size: 5vw; font-family: 'Oswald';">Hallo, Fajar Anugerah</h1>
    </div>
    <div class="line" style="margin-top: 8vw;">
        <div class="order-sm-last ml-5">
            <div class="" style="width: 20vw; height: 20vw;">
                <div id="accordion" class="size" style="font-family: 'Oswald', sans-serif; ">    
                    <h3 style="font-size: 2vw;" id="satu">Aktivitas</h3>
                    <div class="stybro" style="font-family: 'Quicksand', sans-serif; font-size: 1vw; text-align: justify;">
                        <p>Kegiatan yang saya lakukan saat ini:</p>
                        <ul>
                            <li>Bermain Futsal</li>
                            <li>Mendengarkan Musik</li>
                            <li>Kuliah</li>
                        </ul>
                    </div>
                    <h3 style="font-size: 2vw;" id="dua">Organisasi</h3>
                    <div style="font-family: 'Quicksand', sans-serif; font-size: 1vw; text-align: justify;">
                        <p>Kegiatan Organisasi yang pernah saya ikuti:</p>
                        <ul>
                            <li>Depor BEM FASILKOM UI</li>
                            <li>Staf Pertandingan CSL 2019</li>
                            <li>Staf EnS COMPFEST 2019</li>
                        </ul>
                    </div>
                    <h3 style="font-size: 2vw;" id="tiga" >Prestasi</h3>
                    <div style="font-family: 'Quicksand', sans-serif; font-size: 1vw; text-align: justify;">
                        <p>Prestasi yang pernah saya raih:</p>
                        <ul>
                        <li>Juara 2 Tingkat Nasional Pencak Silat 2016</li>
                        <li>Juara 3 Tingkat Kota Pencak Silat 2016</li>
                        <li>Juara 1 Tingkat Kota Pencak Silat 2017</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="status" style="text-align: center;">
        <button style="text-align: center; margin-top: 8vw; font-family: 'Quicksand';" id="ubah">Ubah Tema</button>
        <br>
        <br>
        <br>
        <br>
    </div>  
    
</body>
</html>

lab_8/templates/book.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/styleBook.css'%}">
    <link rel="stylesheet" href="{% static '/css/style.css'%}">
    <!-- <script src="{% static '/js/bbb.js' %}"></script> -->
    <link href="https://fonts.googleapis.com/css?family=Oswald|Quicksand&display=swap" rel="stylesheet">
    <!-- <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script> -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            crossorigin="anonymous"></script>
    <title>Book</title>
</head>
<style>
    button{
        border-radius: 5px;
        background-color: none;
        color: black ;
        border: 1.5px solid black;
    }
    button:hover{
        background-color:#f9e1e0 !important ;
    }
</style>
<body>
    <div class="abc">
        <p class="h1" style="margin-top: 5vw;"> Find Your Favorite Book!</p>
        <input id="search" type="text" class="mt-3" placeholder="Search Book here!"  style="width: 13vw; font-family: 'Quicksand';">
        <!-- <button style="font-family: 'Quicksand', sans-serif; background-color: floralwhite;" class="ml-2" id="button">Submit</button> -->
        <button id="button">Submit</button>
    </div>

    <div class="row mt-5" id="ini">

    </div>
   
    <script>
    $(document).ready(() => {
    $.ajax({
        method: 'GET',
        url: '/dataBuku?key=tintin',
        success: function (result){
            let booksView = $('#ini');
            booksView.empty();
            const resultList = result.items;
            for (let i = 0; i< resultList.length; i++){
                let book = resultList[i].volumeInfo;
                booksView.append(
                    "<div class='col-lg-3 col-sm-4 mb-4'>" +
                    "<div class='card h-75'>" +
                    "<img class='card-img-top h-75' src=" + book.imageLinks.thumbnail + ">" +
                    "<div class='card-body'>" +
                    "<h4 class='card-title'>" + book.title + "</h4>" +
                    "<p class='card-text'>Year Released: " + book.publisher + "</p>" +
                    "<p class='card-text'>Categories: " + book.categories + "</p>" +
                    "<p class='card-text'>Authors: " + book.authors + "</p>" +
                    "</div>" +
                    "</div>" +
                    "</div>"
                );
            }
        }
    });
    $('#button').click(function() {
        event.preventDefault();
        const key = $('#search').val();
        $.ajax({
            method: 'GET',
            url: '/dataBuku?key='+key,
            success: function (result){
                let booksView = $('#ini');
                booksView.empty();
                const resultList = result.items;
                for(let i = 0; i< resultList.length; i++){
                    let book = resultList[i].volumeInfo;
                    booksView.append(
                        "<div class='col-lg-3 col-sm-4 mb-4'>" +
                        "<div class='card h-75'>" +
                        "<img class='card-img-top h-75' src=" + book.imageLinks.thumbnail + ">" +
                        "<div class='card-body'>" +
                        "<h4 class='card-title'>" + book.title + "</h4>" +
                        "<p class='card-text'>Year Released: " + book.publisher + "</p>" +
                        "<p class='card-text'>Categories: " + book.categories + "</p>" +
                        "<p class='card-text'>Authors: " + book.authors + "</p>" +
                        "</div>" +
                        "</div>" +
                        "</div>"
                    );
                }
            }
        });
    });
});
    </script>
</body>
</html>

lab_9/templates/login.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="{% static '/css/styleBook.css'%}">
    
    <script src="{% static '/js/bbb.js' %}"></script> -->
    <link rel="stylesheet" href="{% static '/css/style.css'%}">
    <link href="https://fonts.googleapis.com/css?family=Oswald|Quicksand&display=swap" rel="stylesheet">
    <!-- <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script> -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            crossorigin="anonymous"></script>
    <title>Login Fajar</title>
</head>
<body>
    <div style="text-align: center;" class="status">
        <p class="h1" style="text-align: center;">Login</p>
    
        <form action="" method="POST">
            {% csrf_token %}
            <div class="mb-2">
                <input type="user_id" name="user_id" id="user_id" placeholder="Username" required>
            </div>
            <div>
                <input type="password" name="password" id="password" placeholder="Password" required>
            </div>
                <p>
                    {{user_not_found}}
                </p>
            <button class="btn-secondary" id="login_button">Sign in</button>
            
        </form>
    </div>

</body>
</html>

lab_9/templates/logout.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="{% static '/css/styleBook.css'%}">
    <link rel="stylesheet" href="{% static '/css/style.css'%}"> -->
    <!-- <script src="{% static '/js/bbb.js' %}"></script> -->
    <link href="https://fonts.googleapis.com/css?family=Oswald|Quicksand&display=swap" rel="stylesheet">
    <!-- <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script> -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            crossorigin="anonymous"></script>
    <title>Logout Fajar</title>
</head>
<body>
    <div style="text-align: center;">
        <p class="h1 mt-5 mb-3">Hi {{user.username}} Selamat Datang di Website ini</p> 
    </div>

    <div class="status" style="text-align: center;">
        <form action="/logout/" method="POST">
            {%csrf_token%}
            <button class="btn-secondary" type="submit">Logout</button>
        </form>
    </div>

</body>
</html>